---

- name: Update repo cache
  action: >
    {{ ansible_pkg_mgr }} update_cache=yes

- name: Install SSSD packages
  package:
    name: '{{ item }}'
    state: present
  with_items: '{{ sssd__packages_names|list }}'
