---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-data:
      ignore: '.direnv/'
platforms:
  - name: sssd_install_${MOLECULE_DISTRIBUTION:-ubuntu18}
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-ubuntu18}-ansible:latest"
    command: ${MOLECULE_COMMAND:-""}
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    privileged: true
    pre_build_image: yes
provisioner:
  name: ansible
  options:
    vvv: true
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
