---
dependency:
  name: galaxy
driver:
  name: podman
lint:
  name: yamllint
  options:
    config-data:
      ignore: '.direnv/'
platforms:
  - name: ansible-sssd-test
    image: "quay.io/samdoran/${MOLECULE_DISTRIBUTION:-ubuntu18}-ansible"
    command: ${MOLECULE_COMMAND:-""}
    tty: True
    privileged: True
    pre_build_image: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
