---
- name: Run role
  hosts: all
  any_errors_fatal: true
  tasks:
    - name: Update repo cache
      action: >
        {{ ansible_pkg_mgr }} update_cache=yes cache_valid_time=1800

    - name: Install apparmor
      package:
        name: apparmor
        state: present
      when:
        - ansible_os_family == 'Debian'

    - name: Include ansible-sssd role
      include_role:
        name: ansible-sssd
  vars:
    MOLECULE_TESTRUN: true
    sssd__service_enabled: false
    sssd__domains:
      - contoso.com
    sssd__default_domain: contoso.com
    sssd__services:
      - nss
      - pam
      - ssh
      - sudo
    sssd__services_settings:
      nss:
        reconnection_retries: 3
      pam:
        reconnection_retries: 3
    sssd__domains_settings:
      contoso.com:
        ad_domain: contoso.com
        krb5_realm: contoso.com
    sssd__configure_ssh: true
