---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - role: ansible-sssd
  vars:
    sssd__service_enabled: false
    sssd__domains: 
      - contoso.com
    sssd__default_domain: contoso.com
    sssd__services:
      - nss
      - pam
      - ssh
      - sudo
    sssd__services_settings:
      nss:
        reconnection_retries: 3
      pam:
        reconnection_retries: 3
    sssd__domains_settings:
      contoso.com:
        ad_domain: contoso.com
        krb5_realm: contoso.com
